### PR TITLE
Update package.json, README.md, and Learner.js

### PR DESCRIPTION
**Pull request by Lazerbeak12345**
Update README and add __better documentation__.

### CODE REVIEW

**Comment by Lazerbeak12345** [comment]
Hey Alex, how does the documentation look now? (please note that I don't know what your question was, and I took a guess.)

**Comment by Lazerbeak12345** [comment]
hey alex, you may want to start at line 118

**Comment by NeuroPyrox** [comment]
Sorry for the late review, but I think the reason I'm not understanding the documentation is because I'm used to reading code with lots of examples/unit tests and classes, not because of a lack of comments. Do you mind if I fork it and refactor the code to make unit tests easier for you?

**Comment by Lazerbeak12345** [comment]
Sure, just make sure to do it on your own branch or something, then pull in your changes.

**Pull request merged**
